import AppLayout from '@/components/Layouts/AppLayout'
import Head from 'next/head'
import BackButton from '@/components/BackButton'
import Input from "@/components/Input";
import Button from "@/components/Button";
import InputSelect from "@/components/InputSelect";
import InputFile from "@/components/InputFile";

Create.getLayout = (page) => <AppLayout name="Create">{page}</AppLayout>
export default function Create() {
    return (
        <>
            <Head>
                <title>Create - İmtihan</title>
                <meta
                    name="description"
                    content="Generated by codenteq"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="px-4 pt-16">
                <BackButton href="/admin/company"/>

                <form>
                    <div className="flex items-center justify-between my-4">
                        {/* is active */}
                        <div className="mt-3">
                            <label className="inline-flex items-center">
                                <Input
                                    name="is_active"
                                    type="checkbox"
                                    className="rounded w-2 h-2 border-brand text-brand shadow-sm focus:ring focus:ring-brand focus:ring-opacity-20"
                                />

                                <span className="ml-2 text-sm text-gray-600">
                                Checked for active
                            </span>
                            </label>
                        </div>
                        {/* Button */}
                        <Button>Save</Button>
                    </div>
                    {/* logo */}
                    <InputFile className="my-4">
                        <Input
                            name="logo"
                            type="file"
                            className="hidden"
                            required
                        />
                    </InputFile>
                    <div className="grid gap-4 mb-6 lg:grid-cols-2">
                        {/* name */}
                        <div>
                            <Input
                                name="name"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Name"
                                required
                            />
                        </div>
                        {/* email */}
                        <div>
                            <Input
                                name="email"
                                type="email"
                                className="block mt-1 w-full"
                                placeholder="Email"
                                required
                            />
                        </div>
                        {/* phone */}
                        <div>
                            <Input
                                name="phone"
                                type="phone"
                                className="block mt-1 w-full"
                                placeholder="Phone"
                                required
                            />
                        </div>
                        {/* tax id */}
                        <div>
                            <Input
                                name="tax_id"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Tax id"
                                minLength="11"
                                maxLength="11"
                                required
                            />
                        </div>
                        {/* subdomain */}
                        <div>
                            <Input
                                name="subdomain"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Subdomain"
                                required
                            />
                        </div>
                        {/* web url */}
                        <div>
                            <Input
                                name="web_url"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Web url"
                                required
                            />
                        </div>
                        {/* address */}
                        <div>
                            <Input
                                name="address"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Address"
                                required
                            />
                        </div>
                        {/* zip code */}
                        <div>
                            <Input
                                name="zip_code"
                                type="text"
                                className="block mt-1 w-full"
                                placeholder="Zip code"
                                required
                            />
                        </div>
                        {/* country */}
                        <div>
                            <InputSelect name="country_id" required defaultOption="Choose a country">
                                <option value="tr">Türkiye</option>
                            </InputSelect>
                        </div>
                        {/* city */}
                        <div>
                            <InputSelect name="city_id" required defaultOption="Choose a city">
                                <option value="01">Adana</option>
                            </InputSelect>
                        </div>
                        {/* state */}
                        <div>
                            <InputSelect name="state_id" required defaultOption="Choose a state">
                                <option value="011">Merkez</option>
                            </InputSelect>
                        </div>
                    </div>
                </form>
            </main>
        </>
    )
}
