import AppLayout from '@/components/Layouts/AppLayout'
import Head from 'next/head'
import { useState } from 'react'
import Table from '@/components/Table/Table'
import NavLink from '@/components/NavLink'
import { EllipsisHorizontalIcon } from '@heroicons/react/24/outline'

Index.getLayout = (page) => <AppLayout name="Companies">{page}</AppLayout>
export default function Index() {
    const [users] = useState(() => [
        {
            name: 'Ahmet Sefa',
            surname: 'Arşiv',
            email: 'ahmetarsivpm@gmail.com',
            age: 21
        },
        {
            name: 'Ali',
            surname: 'Karabay',
            email: 'alikarabay77@gmail.com',
            age: 21
        },
        {
            name: 'Tayfun',
            surname: 'Erbilen',
            email: 'te@gmail.com',
            age: 29
        },
        {
            name: 'Mehmet',
            surname: 'Seven',
            email: 'mseven@gmail.com',
            age: 29
        },
        {
            name: 'Gökhan',
            surname: 'Kandemir',
            email: 'gkandemir@gmail.com',
            age: 35
        },
        {
            name: 'Ahmet',
            surname: 'Tarık G.',
            email: 'atg@gmail.com',
            age: 24
        }
    ])
    return (
        <>
            <Head>
                <title>Companies - İmtihan</title>
                <meta
                    name="description"
                    content="Generated by codenteq"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="pt-16">
                <div className="flex justify-end px-4">
                    <NavLink name="Create" href="/admin/company/create"/>
                </div>

                <Table
                    searchable={true}
                    head={[
                        {name: 'Ad-Soyad', sortable: true},
                        {name: 'E-posta'},
                        {name: 'Yaş', sortable: true},
                        {name: 'İşlemler', width: 200}
                    ]}
                    body={users && users.map((user, key) => ([
                        <div key={`${user.name} ${user.surname}`}>{user.name} {user.surname}</div>,
                        user.email,
                        <div searchableText={`Yaş ${user.age}`}>{user.age}</div>,
                        [
                            <button id="tableDropdownMenu" data-dropdown-toggle="dropdownDots" type="button">
                                <EllipsisHorizontalIcon className="w-6 h-6"/>
                            </button>,

                            <div id="dropdownDots" className="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 -translate-x-10">
                                <ul className="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="tableDropdownMenu">
                                    <li>
                                        <a href="#" className="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit</a>
                                    </li>
                                    <li>
                                        <a href="#" className="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Remove</a>
                                    </li>
                                </ul>
                            </div>
                        ]
                    ]))}
                />
            </main>
        </>
    )
}
